# -*- coding: utf-8 -*-
"""
Created on Thu May  5 09:56:03 2022

@author: Administrator
"""

import streamlit as st
import code
import time
import os
os.chdir("E:\Ivy-Professional-School\Python\ML\Activity Recognition System\Code")
st.title("Activity Recognition of Human Using Logistic Regression!!")
st.text('''This dataset represents a real-life benchmark in the area of Activity Recognition applications

The classification tasks consist in predicting the activity performed by the user from time-series generated by a Wireless Sensor Network (WSN), according to the EvAAL competition technical annex 

In our activity recognition system we use information coming the implicit alteration of the wireless channel due to the movements of the user. The devices measure the RSS of the beacon packets they exchange among themselves in the WSN
We collect RSS data using IRIS nodes embedding a Chipcon AT86RF230 radio subsystem that implements the IEEE 802.15.4 standard and programmed with a TinyOS firmware. They are placed on the userâ€™s chest and ankles. For the purpose of communications, the beacon packets are exchanged by using a simple virtual token protocol that completes its execution in a time slot of 50 milliseconds. A modified version of the Spin ([Web Link]) token-passing protocol is used to schedule node transmission, in order to prevent packet collisions and maintain high data collection rate. When an anchor is transmitting, all other anchors receive the packet and perform the RSS measurements. The payload of the transmitting packet is the set of RSS values between the transmitting node and the other sensors sampled during the previous cycle.

From the raw data we extract time-domain features to compress the time series and slightly remove noise and correlations.

We choose an epoch time of 250 milliseconds according to the EVAAL technical annex. In such a time slot we elaborate 5 samples of RSS (sampled at 20 Hz) for each of the three couples of WSN nodes (i.e. Chest-Right Ankle, Chest-Left Ankle, Right Ankle-Left Ankle). The features include the mean value and standard deviation for each reciprocal RSS reading from worn WSN sensors.

For each activity 15 temporal sequences of input RSS data are present. The dataset contains 480 sequences, for a total number of 42240 instances.''')

st.subheader("Please give your inputs and we predict your activity!")
avg_rss12=st.number_input(label="Average Receiever Signal Strength 12",step=1.,format="%.2f")
var_rss12=st.number_input(label="Variance Receiever Signal Strength 12",step=1.,format="%.2f")
avg_rss13=st.number_input(label="Average Receiever Signal Strength 13",step=1.,format="%.2f")
var_rss13=st.number_input(label="variance Receiever Signal Strength 13",step=1.,format="%.2f")
avg_rss23=st.number_input(label="Average Receiever Signal Strength 23",step=1.,format="%.2f")
var_rss23=st.number_input(label="Variance Receiever Signal Strength 23",step=1.,format="%.2f")

if st.button("Predict"):
    prediction=code.pred(avg_rss12,var_rss12,avg_rss13,var_rss13,avg_rss23,var_rss23)
    st.success(f"Predicted {prediction}")